### ISSUE TITLE
does not destroy properly

### ISSUE THREAD

**Issue by l300lvl** [isDipesh/gnome-shell-extension-force-quit#1]
there are multiple problems with this I have posted about on E.G.O, one of which is that it doesn't disable properly and a restart on shell is required.

The second is it doesn't seem to function properly at all. I notice it was recent updated to only use xkill now but for some reason that only worked the very first time I installed this, and not a single time after. I have removed it and reinstalled numerous times, and unless theres something hidden somewhere it would seem something systemwide is blocking this from running xkill, if that's even possible?

**Comment by isDipesh** [comment]
I have updated the extension.
It is now destroyed properly on disabling.

xkill isn't running properly because it can't grab the cursor, 'unable to grab cursor' is what it returns. It works on double-click on my system though. I think it works like that because on double-clicking, the focus is already on the Force Quit button after the first click, then only it can grab the cursor.

Try if double click works on your system too and please report back.

Thank you very much for reporting :)

**Comment by l300lvl** [comment]
It does seem to work properly now. The only problem I see now is you should work on placement, i.e it doesn't get along well with other extensions. But for now it works, which is what matters. Thanks!
